import { MetadataRoute } from 'next';

/**
 * Dynamic sitemap generation for SEO
 * This will be automatically generated by Next.js
 */
export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = process.env.NEXT_PUBLIC_SITE_URL || 'https://aicalculator.com';

  // Main pages
  const routes = [
    '',
    '/calculators',
    '/blog',
    '/about',
    '/contact',
  ].map((route) => ({
    url: `${baseUrl}${route}`,
    lastModified: new Date(),
    changeFrequency: 'daily' as const,
    priority: route === '' ? 1 : 0.8,
  }));

  // Calculator pages
  const calculators = [
    '/bmi-calculator',
    '/loan-calculator',
    '/percentage-calculator',
    '/calorie-calculator',
    '/tax-calculator',
    '/age-calculator',
    '/mortgage-calculator',
    '/retirement-calculator',
    '/investment-calculator',
    '/pregnancy-calculator',
    '/ratio-calculator',
    '/square-root-calculator',
    '/statistics-calculator',
    '/volume-calculator',
    '/triangle-calculator',
    '/circle-calculator',
    '/pythagorean-calculator',
    '/compound-interest-calculator',
    '/future-value-calculator',
    '/present-value-calculator',
    '/ideal-weight-calculator',
    '/lease-calculator',
    '/breakeven-calculator',
    '/profit-margin-calculator',
    '/markup-calculator',
    '/payroll-calculator',
    '/sales-tax-calculator',
    '/discount-calculator',
    '/cash-flow-calculator',
    '/depreciation-calculator',
    '/overtime-calculator',
    '/amortization-calculator',
  ].map((route) => ({
    url: `${baseUrl}${route}`,
    lastModified: new Date(),
    changeFrequency: route === '/breakeven-calculator' || route === '/profit-margin-calculator' || route === '/markup-calculator' || route === '/payroll-calculator' || route === '/sales-tax-calculator' || route === '/discount-calculator' || route === '/cash-flow-calculator' || route === '/depreciation-calculator' || route === '/overtime-calculator' || route === '/amortization-calculator' ? 'monthly' as const : 'weekly' as const,
    priority: route === '/breakeven-calculator' || route === '/profit-margin-calculator' || route === '/markup-calculator' || route === '/payroll-calculator' || route === '/sales-tax-calculator' || route === '/discount-calculator' || route === '/cash-flow-calculator' || route === '/depreciation-calculator' || route === '/overtime-calculator' || route === '/amortization-calculator' ? 0.8 : 0.9,
  }));

  return [...routes, ...calculators];
}
