// Complete calculator database with keywords for smart search
export interface Calculator {
  name: string;
  url: string;
  keywords: string[];
  category: string;
  icon: string;
}

export const allCalculators: Calculator[] = [
  // Financial Calculators
  { name: 'Mortgage Calculator', url: '/mortgage-calculator', keywords: ['home loan', 'house payment', 'mortgage', 'home', 'property', 'real estate'], category: 'Financial', icon: '🏠' },
  { name: 'Loan Calculator', url: '/loan-calculator', keywords: ['borrow', 'lending', 'personal loan', 'auto loan', 'debt'], category: 'Financial', icon: '💰' },
  { name: 'EMI Calculator', url: '/emi-calculator', keywords: ['monthly installment', 'equated monthly', 'payment plan', 'installment'], category: 'Financial', icon: '💳' },
  { name: 'Interest Calculator', url: '/interest-calculator', keywords: ['compound', 'simple interest', 'earnings', 'investment return'], category: 'Financial', icon: '📈' },
  { name: 'Salary Calculator', url: '/salary-calculator', keywords: ['wage', 'income', 'pay', 'hourly', 'annual', 'biweekly'], category: 'Financial', icon: '💵' },
  { name: 'Income Tax Calculator', url: '/tax-calculator', keywords: ['tax', 'income tax', 'federal tax', 'state tax', 'tax return', 'deduction'], category: 'Financial', icon: '🧾' },
  { name: 'Savings Calculator', url: '/savings-calculator', keywords: ['save money', 'savings plan', 'goal', 'deposit'], category: 'Financial', icon: '🐷' },
  { name: 'Retirement Calculator', url: '/retirement-calculator', keywords: ['401k', 'pension', 'retirement plan', 'nest egg'], category: 'Financial', icon: '🏖️' },
  { name: 'Investment Calculator', url: '/investment-calculator', keywords: ['invest', 'portfolio', 'stock', 'return', 'profit'], category: 'Financial', icon: '📊' },
  { name: 'Auto Loan Calculator', url: '/auto-loan-calculator', keywords: ['car loan', 'vehicle', 'car payment', 'auto finance'], category: 'Financial', icon: '🚗' },
  { name: 'Payment Calculator', url: '/payment-calculator', keywords: ['monthly payment', 'installment', 'amortization'], category: 'Financial', icon: '💳' },
  { name: 'Discount Calculator', url: '/discount-calculator', keywords: ['sale', 'percentage off', 'coupon', 'markdown'], category: 'Financial', icon: '🏷️' },
  { name: 'Debt Payoff Calculator', url: '/debt-payoff-calculator', keywords: ['pay off debt', 'credit card', 'debt free', 'snowball'], category: 'Financial', icon: '💸' },
  { name: 'Mortgage Payoff Calculator', url: '/mortgage-payoff-calculator', keywords: ['pay off mortgage', 'early payoff', 'extra payment'], category: 'Financial', icon: '🏡' },
  { name: 'Refinance Calculator', url: '/refinance-calculator', keywords: ['refi', 'refinancing', 'lower rate', 'break even'], category: 'Financial', icon: '🔄' },
  { name: '401k Calculator', url: '/401k-calculator', keywords: ['retirement savings', 'employer match', 'retirement plan'], category: 'Financial', icon: '🏦' },
  { name: 'Paycheck Calculator', url: '/pay-calculator', keywords: ['paycheck', 'net pay', 'take home', 'withholding'], category: 'Financial', icon: '💰' },
  { name: 'Currency Converter', url: '/currency-converter', keywords: ['exchange rate', 'forex', 'foreign exchange', 'USD', 'EUR', 'GBP', 'currency exchange', 'money converter'], category: 'Financial', icon: '💱' },
  { name: 'ROI Calculator', url: '/roi-calculator', keywords: ['return on investment', 'ROI', 'investment return', 'profit calculator', 'annualized return', 'investment performance', 'net profit', 'ROI percentage'], category: 'Financial', icon: '📈' },
  { name: 'Credit Card Calculator', url: '/credit-card-calculator', keywords: ['credit card payoff', 'credit card debt', 'minimum payment', 'credit card interest', 'balance transfer', 'pay off credit card', 'credit card apr', 'debt payoff'], category: 'Financial', icon: '💳' },
  { name: 'Inflation Calculator', url: '/inflation-calculator', keywords: ['inflation', 'purchasing power', 'CPI', 'consumer price index', 'inflation rate', 'cost of living', 'money value', 'inflation adjustment', 'future value'], category: 'Financial', icon: '📈' },
  { name: 'Business Loan Calculator', url: '/business-loan-calculator', keywords: ['business loan', 'commercial loan', 'SBA', 'APR', 'origination fee', 'loan payment', 'bi-weekly payments', 'weekly payments', 'amortization', 'prepayment'], category: 'Financial', icon: '🏢' },
  { name: 'Home Loan Calculator', url: '/home-loan-calculator', keywords: ['home loan', 'house loan', 'residential loan', 'property loan', 'home mortgage', 'house payment', 'home finance', 'property finance'], category: 'Financial', icon: '🏠' },
  
  // Health & Fitness
  { name: 'BMI Calculator', url: '/bmi-calculator', keywords: ['body mass index', 'weight', 'obesity', 'underweight', 'healthy weight'], category: 'Health', icon: '⚖️' },
  { name: 'Calorie Calculator', url: '/calorie-calculator', keywords: ['diet', 'nutrition', 'TDEE', 'BMR', 'weight loss', 'calories'], category: 'Health', icon: '🍎' },
  { name: 'BMR Calculator', url: '/bmr-calculator', keywords: ['basal metabolic rate', 'metabolism', 'resting', 'energy'], category: 'Health', icon: '🔥' },
  { name: 'TDEE Calculator', url: '/tdee-calculator', keywords: ['total daily energy expenditure', 'TDEE', 'calorie needs', 'activity level', 'cutting', 'bulking', 'maintenance'], category: 'Health', icon: '⚡' },
  { name: 'Macro Calculator', url: '/macro-calculator', keywords: ['macros', 'macronutrients', 'protein', 'carbs', 'fats', 'IIFYM', 'flexible dieting', 'nutrition plan', 'meal plan'], category: 'Health', icon: '🍗' },
  { name: 'Body Fat Calculator', url: '/body-fat-calculator', keywords: ['fat percentage', 'body composition', 'lean mass'], category: 'Health', icon: '💪' },
  { name: 'Weight Calculator', url: '/weight-calculator', keywords: ['ideal weight', 'target weight', 'healthy weight'], category: 'Health', icon: '⚖️' },
  { name: 'Pace Calculator', url: '/pace-calculator', keywords: ['running', 'jogging', 'speed', 'marathon', 'race'], category: 'Health', icon: '🏃' },
  { name: 'Protein Calculator', url: '/protein-calculator', keywords: ['protein', 'daily protein', 'protein intake', 'protein needs', 'protein requirement', 'protein per day', 'muscle gain', 'protein for weight loss', 'protein calculator cutting', 'protein calculator bulking'], category: 'Health', icon: '🥩' },
  { name: 'Pregnancy Calculator', url: '/pregnancy-calculator', keywords: ['pregnancy calculator', 'due date calculator', 'pregnancy week calculator', 'conception calculator', 'pregnancy due date', 'when is my due date', 'how many weeks pregnant', 'pregnancy calendar', 'trimester calculator', 'gestational age calculator', 'LMP calculator', 'ultrasound due date'], category: 'Health', icon: '🤰' },
  { name: 'Ideal Weight Calculator', url: '/ideal-weight-calculator', keywords: ['ideal weight calculator', 'ideal body weight', 'target weight calculator', 'healthy weight calculator', 'perfect weight calculator', 'ideal weight formula', 'robinson formula', 'devine formula', 'miller formula', 'hamwi formula', 'broca formula', 'ideal weight for height', 'healthy weight range', 'body frame size', 'weight goal calculator', 'optimal weight'], category: 'Health', icon: 'Heart' },
  { name: 'Lease Calculator', url: '/lease-calculator', keywords: ['lease calculator', 'lease vs buy calculator', 'auto lease calculator', 'car lease calculator', 'equipment lease calculator', 'lease payment calculator', 'lease analysis', 'lease vs purchase', 'lease comparison', 'monthly lease payment', 'lease terms calculator', 'residual value calculator', 'lease cost calculator', 'commercial lease calculator', 'lease decision tool'], category: 'Financial', icon: 'Car' },
  { name: 'Break-even Calculator', url: '/breakeven-calculator', keywords: ['break even', 'breakeven point', 'profit analysis', 'business planning', 'cost analysis', 'revenue target', 'fixed costs', 'variable costs', 'contribution margin', 'business strategy', 'startup planning', 'financial planning', 'profitability', 'sales target', 'pricing strategy'], category: 'Financial', icon: 'Target' },
  { name: 'Profit Margin Calculator', url: '/profit-margin-calculator', keywords: ['profit margin', 'gross margin', 'net margin', 'operating margin', 'markup calculator', 'business profitability', 'pricing optimization', 'cost analysis', 'revenue optimization', 'industry benchmarks', 'margin analysis', 'profit planning', 'business metrics', 'financial analysis', 'pricing strategy', 'profitability calculator', 'business performance', 'profit optimization', 'margin improvement', 'business calculator'], category: 'Financial', icon: 'Percent' },
  { name: 'Markup Calculator', url: '/markup-calculator', keywords: ['markup calculator', 'markup percentage calculator', 'cost calculator', 'selling price calculator', 'pricing calculator', 'profit markup', 'business markup', 'retail markup', 'wholesale markup', 'markup vs margin', 'pricing strategy', 'cost analysis', 'profit calculation', 'business calculator', 'pricing optimization', 'markup formula', 'retail pricing', 'product pricing', 'markup analysis', 'business profitability'], category: 'Financial', icon: 'DollarSign' },
  { name: 'Payroll Calculator', url: '/payroll-calculator', keywords: ['payroll calculator', 'net pay calculator', 'salary calculator', 'tax calculator', 'paycheck calculator', 'take home pay calculator', 'federal tax calculator', 'state tax calculator', 'social security calculator', 'medicare calculator', 'payroll tax calculator', '401k calculator', 'health insurance deduction', 'gross to net calculator', 'employee payroll', 'payroll deductions', 'withholding calculator', 'FICA calculator', 'payroll processing', 'wage calculator'], category: 'Financial', icon: 'Users' },
  { name: 'Sales Tax Calculator', url: '/sales-tax-calculator', keywords: ['sales tax calculator', 'state sales tax', 'local sales tax', 'tax calculator', 'sales tax rate', 'add sales tax', 'remove sales tax', 'tax compliance', 'business tax calculator', 'retail tax calculator', 'ecommerce tax calculator', 'city sales tax', 'county sales tax', 'tax rate lookup', 'sales tax by state', 'tax calculation tool', 'point of sale tax', 'merchant tax calculator', 'tax inclusive pricing', 'tax exclusive pricing'], category: 'Financial', icon: 'Calculator' },
  { name: 'Discount Calculator', url: '/discount-calculator', keywords: ['discount calculator', 'sale price calculator', 'percent off calculator', 'savings calculator', 'price discount calculator', 'calculate discount percentage', 'final price calculator', 'markdown calculator', 'sale calculator', 'percent discount', 'how much is 20 percent off', 'discount formula', 'multiple discount calculator', 'black friday calculator', 'clearance price calculator', 'shopping calculator', 'deal calculator', 'coupon calculator', 'price reduction calculator', 'bargain calculator'], category: 'Financial', icon: 'Tag' },
  { name: 'Cash Flow Calculator', url: '/cash-flow-calculator', keywords: ['cash flow calculator', 'npv calculator', 'irr calculator', 'investment calculator', 'payback period calculator', 'profitability index calculator', 'discounted cash flow', 'net present value calculator', 'internal rate of return', 'investment analysis', 'financial modeling', 'capital budgeting', 'project evaluation', 'investment appraisal', 'dcf calculator', 'business valuation', 'financial planning', 'investment decision', 'cash flow analysis', 'roi calculator'], category: 'Financial', icon: 'TrendingUp' },
  { name: 'Depreciation Calculator', url: '/depreciation-calculator', keywords: ['depreciation calculator', 'straight line depreciation', 'double declining balance', 'sum of years digits', 'units of production depreciation', 'depreciation schedule', 'tax depreciation calculator', 'asset depreciation', 'depreciation methods', 'tax savings calculator', 'business depreciation', 'accounting depreciation', 'capital asset depreciation', 'depreciation expense', 'tax deduction calculator', 'asset management', 'depreciation comparison', 'accelerated depreciation', 'depreciation analysis', 'business tax calculator'], category: 'Financial', icon: 'TrendingDown' },
  { name: 'Overtime Calculator', url: '/overtime-calculator', keywords: ['overtime calculator', 'overtime pay calculator', 'time and a half calculator', 'double time calculator', 'labor law compliance', 'FLSA calculator', 'overtime rate calculator', 'payroll calculator', 'wage calculator', 'overtime cost calculator', 'employee overtime', 'overtime premium', 'labor cost calculator', 'overtime analysis', 'work hours calculator', 'overtime compliance', 'california overtime', 'federal overtime rules', 'overtime multiplier', 'business labor costs'], category: 'Financial', icon: 'Clock' },
  { name: 'Amortization Calculator', url: '/amortization-calculator', keywords: ['amortization calculator', 'loan amortization schedule', 'mortgage payment calculator', 'loan payment schedule', 'extra payment calculator', 'loan payoff calculator', 'amortization table', 'mortgage amortization', 'loan interest calculator', 'payment breakdown calculator', 'principal and interest calculator', 'loan term calculator', 'early payoff calculator', 'biweekly payment calculator', 'loan analysis tool', 'mortgage schedule', 'debt payoff planner', 'loan comparison calculator', 'interest savings calculator', 'refinance analysis'], category: 'Financial', icon: 'FileText' },
  
  // Math & Numbers
  { name: 'Percentage Calculator', url: '/percentage-calculator', keywords: ['percent', 'percentage', 'fraction', 'ratio'], category: 'Math', icon: '%' },
  { name: 'Fraction Calculator', url: '/fraction-calculator', keywords: ['fractions', 'mixed numbers', 'simplify', 'reduce'], category: 'Math', icon: '➗' },
  { name: 'Ratio Calculator', url: '/ratio-calculator', keywords: ['ratio calculator', 'proportion calculator', 'simplify ratio', 'ratio solver', 'cross multiplication', 'equivalent ratios', 'ratio comparison', 'ratio to percentage', 'aspect ratio', 'golden ratio'], category: 'Math', icon: '⚖️' },
  { name: 'Square Root Calculator', url: '/square-root-calculator', keywords: ['square root calculator', 'nth root calculator', 'perfect square calculator', 'cube root calculator', 'radical calculator', 'root solver', 'square root finder', 'irrational numbers', 'principal square root', 'radical simplifier'], category: 'Math', icon: '√' },
  { name: 'Statistics Calculator', url: '/statistics-calculator', keywords: ['statistics calculator', 'descriptive statistics', 'mean calculator', 'median calculator', 'standard deviation calculator', 'variance calculator', 'quartile calculator', 'statistical analysis', 'data analysis tool', 'outlier detection'], category: 'Math', icon: '📊' },
  { name: 'Scientific Calculator', url: '/scientific-calculator', keywords: ['scientific', 'trig', 'logarithm', 'advanced math'], category: 'Math', icon: '🔬' },
  { name: 'Average Calculator', url: '/average-calculator', keywords: ['mean', 'median', 'mode', 'statistics', 'average'], category: 'Math', icon: '📊' },
  { name: 'Area Calculator', url: '/area-calculator', keywords: ['area', 'area of rectangle', 'area of circle', 'area of triangle', 'area formula', 'geometry', 'shape area', 'rectangle area', 'circle area', 'triangle area', 'trapezoid area', 'parallelogram area', 'ellipse area'], category: 'Math', icon: '📐' },
  { name: 'Quadratic Formula Calculator', url: '/quadratic-formula-calculator', keywords: ['quadratic formula', 'quadratic equation', 'solve ax^2 + bx + c', 'discriminant', 'b^2 - 4ac', 'quadratic roots', 'complex roots', 'algebra'], category: 'Math', icon: '➗' },
  { name: 'Standard Deviation Calculator', url: '/standard-deviation-calculator', keywords: ['standard deviation', 'standard deviation calculator', 'variance calculator', 'calculate standard deviation', 'sample standard deviation', 'population standard deviation', 'std dev calculator', 'sigma calculator', 'statistics calculator', 'data spread', 'outlier detection', 'statistical analysis'], category: 'Math', icon: '📊' },
  { name: 'Volume Calculator', url: '/volume-calculator', keywords: ['volume calculator', '3d shape calculator', 'cube volume', 'sphere volume', 'cylinder volume', 'cone volume', 'volume formula', 'cubic volume', 'geometry calculator', 'surface area calculator', 'material calculator', 'concrete calculator', 'paint calculator', 'capacity calculator', '3d geometry', 'rectangular prism', 'triangular prism', 'pyramid volume', 'hemisphere volume', 'ellipsoid volume'], category: 'Math', icon: '📦' },
  { name: 'Triangle Calculator', url: '/triangle-calculator', keywords: ['triangle calculator', 'triangle solver', 'SSS triangle', 'SAS triangle', 'ASA triangle', 'triangle area calculator', 'triangle perimeter', 'law of cosines', 'law of sines', 'triangle angles', 'triangle sides', 'solve triangle', 'triangle formula', 'geometry calculator', 'trigonometry calculator', 'triangle type', 'equilateral triangle', 'isosceles triangle', 'scalene triangle', 'right triangle'], category: 'Math', icon: '📐' },
  { name: 'Circle Calculator', url: '/circle-calculator', keywords: ['circle calculator', 'circle area calculator', 'circumference calculator', 'circle diameter calculator', 'radius calculator', 'circle formula', 'area of circle', 'circumference formula', 'pi calculator', 'geometry calculator', 'circle measurements', 'circle properties', 'circle math', 'circular area', 'perimeter of circle', 'circle geometry', 'pi value', 'circle radius', 'circle circumference'], category: 'Math', icon: '⭕' },
  { name: 'Pythagorean Theorem Calculator', url: '/pythagorean-calculator', keywords: ['pythagorean theorem calculator', 'right triangle calculator', 'hypotenuse calculator', 'pythagorean calculator', 'find missing side triangle', 'a squared plus b squared equals c squared', 'right triangle solver', 'triangle leg calculator', 'pythagorean theorem formula', 'geometry calculator', '3-4-5 triangle', 'right angle triangle', 'pythagorean triple', 'triangle calculator', 'math calculator'], category: 'Math', icon: '📐' },
  { name: 'Compound Interest Calculator', url: '/compound-interest-calculator', keywords: ['compound interest calculator', 'investment calculator', 'compound interest formula', 'investment growth calculator', 'retirement calculator', 'savings calculator', 'interest calculator', 'compound annual growth rate', 'time value of money', 'investment returns', 'financial calculator', 'compound vs simple interest', 'investment planning', 'wealth building calculator', 'money growth calculator'], category: 'Financial', icon: '📈' },
  { name: 'Future Value Calculator', url: '/future-value-calculator', keywords: ['future value', 'investment growth', 'fv calculator', 'time value money', 'investment projection', 'financial planning', 'compound growth', 'investment calculator', 'wealth projection', 'retirement planning'], category: 'Financial', icon: 'TrendingUp' },
  { name: 'Present Value Calculator', url: '/present-value-calculator', keywords: ['present value', 'npv calculator', 'net present value', 'discounted cash flow', 'dcf calculator', 'investment analysis', 'pv calculator', 'discount rate', 'profitability index', 'investment decision', 'bond valuation', 'project evaluation', 'time value money', 'financial analysis'], category: 'Financial', icon: 'TrendingDown' },
  { name: 'Graphing Calculator', url: '/graphing-calculator', keywords: ['graphing calculator', 'function plotter', 'graph maker', 'plot functions', 'function grapher', 'mathematical graphing', 'equation plotter', 'graph functions online', 'scientific graphing calculator', 'function plotting tool', 'algebra graphing', 'calculus graphing', 'trigonometry graphs', 'polynomial graphing', 'graph analysis'], category: 'Math', icon: '📈' },
  
  // Time & Date
  { name: 'Age Calculator', url: '/age-calculator', keywords: ['how old', 'birthday', 'years old', 'age difference'], category: 'Other', icon: '🎂' },
  { name: 'Date Calculator', url: '/date-calculator', keywords: ['days between', 'date difference', 'add days', 'subtract days'], category: 'Other', icon: '📅' },
  { name: 'Time Calculator', url: '/time-calculator', keywords: ['hours', 'minutes', 'duration', 'time difference'], category: 'Other', icon: '⏰' },
  
  // Academic
  { name: 'Grade Calculator', url: '/grade-calculator', keywords: ['grade', 'score', 'test', 'weighted average', 'final grade'], category: 'Academic', icon: '📝' },
  { name: 'GPA Calculator', url: '/gpa-calculator', keywords: ['grade point average', 'cumulative GPA', 'semester'], category: 'Academic', icon: '🎓' },
  
  // Other
  { name: 'Tip Calculator', url: '/tip-calculator', keywords: ['gratuity', 'service charge', 'tip', 'restaurant'], category: 'Other', icon: '🍴' },
  { name: 'Unit Converter', url: '/unit-converter', keywords: ['convert', 'units', 'length', 'weight', 'temperature', 'measurement'], category: 'Other', icon: '🔀' },
  { name: 'Square Footage Calculator', url: '/square-footage-calculator', keywords: ['area', 'square feet', 'room size', 'flooring'], category: 'Other', icon: '📐' },
];

